### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by tsiskrelir** [umdevelopera/um-polylang#5]
Fatal error: Uncaught Error: Class 'um_ext\um_polylang\core\Fields' not found in /home/certifie/public_html/New/wp-content/plugins/um-polylang-main/includes/core/class-um-polylang.php:61 
Stack trace: 
```
#0 /home/certifie/public_html/New/wp-content/plugins/um-polylang-main/includes/core/class-um-polylang.php(46): UM_Polylang->fields() 
#1 /home/certifie/public_html/New/wp-content/plugins/um-polylang-main/includes/core/class-um-polylang.php(35): UM_Polylang->__construct() 
#2 /home/certifie/public_html/New/wp-content/plugins/ultimate-member/includes/class-init.php(155): UM_Polylang::instance() 
#3 /home/certifie/public_html/New/wp-content/plugins/um-polylang-main/um-polylang.php(78): UM->set_class('Polylang', true) 
#4 /home/certifie/public_html/New/wp-includes/class-wp-hook.php(324): um_polylang_init('') 
#5 /home/certifie/public_html/New/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) 
#6 /home/certifie/public_html/New/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#7 /home/certifie/public_html/New/ in /home/certifie/public_html/New/wp-content/plugins/um-polylang-main/includes/core/class-um-polylang.php on line 61
```

**Comment by umdevelopera** [comment]
Hello @tsiskrelir 
It looks like the issue #2. This has been fixed. Please try a newer version from the branch [fix/class_not_found](https://github.com/umdevelopera/um-polylang/tree/fix/class_not_found)
Does an issue go away?
Thank you
